#!/bin/bash
#ddev-generated

## Description: Run Playwright tests inside the Playwright container
## Usage: playwright [flags] [args]
## Example: "ddev playwright --help" or "ddev playwright test"
## ExecRaw: true

set -e

cd test/playwright || exit 1

if [ -f yarn.lock ]; then
  yarn && yarn playwright "$@"
else
  npm ci && npx playwright "$@"
fi